#pragma once

#include "common_def.h"
#include "common_vtk.h"
#include "common_print.h"

#ifdef MESHLIBS_EXPORTS
#include "../meshMiscellUtils/include/meshMiscellUtils.h"
#include "../meshlinalg/include/meshlinalg.h"
#include "../meshVtkUtils/include/meshVtkUtils.h"
#include "../meshIglUtils/include/meshIglUtils.h"
#include "../meshIO/include/meshIO.h"
#include "../meshDeform/include/meshDeform.h"
#include "../meshMorphing/include/meshMorphing.h"
#include "../meshRemeshing/include/meshRemeshing.h"
#include "../meshUndercut/include/meshUndercut.h"
#include "../meshResample/include/meshResample.h"
#include "../meshUndercut/include/meshUndercut.h"
#include "../meshRegistration/include/meshRegistration.h"
#include "../meshSculpt/include/meshSculpt.h"
#include "../meshCutter/include/meshCutter.h"
#include "../meshFilter/include/meshFilter.h"
#include "../meshImage/include/meshImage.h"
#include "../meshTree/include/meshTree.h"
#include "../meshCrownDesign/include/meshCrownDesign.h"
#include "../meshICP/include/meshICP.h"
#include "../meshDrill/include/meshDrill.h"
#else
#include "meshMiscellUtils.h"
#include "meshlinalg.h"
#include "meshVtkUtils.h"
#include "meshIglUtils.h"
#include "meshIO.h"
#include "meshDeform.h"
#include "meshMorphing.h"
#include "meshRemeshing.h"
#include "meshUndercut.h"
#include "meshResample.h"
#include "meshUndercut.h"
#include "meshRegistration.h"
#include "meshSculpt.h"
#include "meshCutter.h"
#include "meshFilter.h"
#include "meshImage.h"
#include "meshTree.h"
#include "meshCrownDesign.h"
#include "meshICP.h"
#include "meshDrill.h"

//#include "meshCrownPlanning.h" // EcoCAD - LibraryManger.lib 이 필요하므로 별도로 포함처리해야한다.
#endif // 
//#include "meshK"